sudo: required
env:
- GHCVER=7.6.3
- GHCVER=7.8.4
- GHCVER=7.10.3
- GHCVER=8.0.2
- GHCVER=head

matrix:
  allow_failures:
  - env: GHCVER=head

script:
- wget https://raw.github.com/ndmitchell/neil/master/travis.sh -O - --quiet | sh
